instructions:
  - "This repository follows Specification-Driven Development (SDD). All changes must start with a specification in `specs/` directory."
  - "This is a Deno project. Never suggest npm packages or Node.js dependencies. Use Deno standard library only."
  - "Before making changes, run the following checks:"
  - "  - `deno test --allow-read --allow-write` - Run all tests (maintain >80% coverage)"
  - "  - `deno lint` - Lint all files"
  - "  - `deno fmt --check` - Check code formatting"
  - "  - `deno check mod.ts` - Type check entry point (once mod.ts exists)"
  - "Changes must pass automatic checks run by GitHub Actions before they can be merged."
  - "Deno requires explicit permissions. Common permissions: `--allow-read`, `--allow-write`, `--allow-env`"
  - "For help, see the README, review `.github/copilot-instructions.md`, or open an onboarding issue."
