name: PR Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.40.x

      - name: Check formatting
        run: deno fmt --check

      - name: Lint code
        run: deno lint

      - name: Type check
        run: |
          if [ -f mod.ts ]; then
            deno check mod.ts
          else
            echo "mod.ts not found, skipping type check"
          fi

      - name: Run tests
        run: |
          if [ -d tests ]; then
            deno test --allow-read --allow-write
          else
            echo "No tests directory found, skipping tests"
          fi
